name: Build Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables
        run: python build.py

      - name: Create Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer.iss

      - name: Upload Single-File Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/onefile/EtsyTrackr.exe

      - name: Upload Installer Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Output/EtsyTrackr_Setup.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse libfuse2 python3-tk python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build AppImage
        run: python build.py --mode appimage

      - name: Upload AppImage Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/appimage/EtsyTrackr-x86_64.AppImage

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: 3.11.8

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Build executable
  #       run: python build.py

  #     - name: Create DMG
  #       run: |
  #         # Free up more space
  #         df -h
  #         sudo rm -rf /usr/local/.ghcup
  #         sudo rm -rf /usr/local/share/powershell
  #         sudo rm -rf /usr/local/share/chromium
  #         sudo rm -rf /usr/local/lib/node_modules
  #         sudo rm -rf /Library/Developer/CommandLineTools
  #         sudo rm -rf /usr/share/dotnet
  #         sudo rm -rf /usr/share/swift
  #         brew cleanup
  #         df -h
          
  #         # Create a smaller working directory
  #         WORK_DIR="/private/tmp/etsytrackr_build"
  #         sudo mkdir -p "$WORK_DIR"
  #         sudo chmod 777 "$WORK_DIR"
          
  #         # Move necessary files to working directory
  #         cp -r dist/EtsyTrackr "$WORK_DIR/"
  #         cp assets/icon.png "$WORK_DIR/"
  #         cd "$WORK_DIR"
          
  #         # Create app bundle
  #         mkdir -p EtsyTrackr.app/Contents/{MacOS,Resources}
  #         mv EtsyTrackr EtsyTrackr.app/Contents/MacOS/
  #         cp icon.png EtsyTrackr.app/Contents/Resources/
          
  #         # Create Info.plist
  #         cat > EtsyTrackr.app/Contents/Info.plist << EOF
  #         <?xml version="1.0" encoding="UTF-8"?>
  #         <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  #         <plist version="1.0">
  #         <dict>
  #             <key>CFBundleExecutable</key>
  #             <string>EtsyTrackr</string>
  #             <key>CFBundleIconFile</key>
  #             <string>icon.png</string>
  #             <key>CFBundleIdentifier</key>
  #             <string>com.go2engle.etsytrackr</string>
  #             <key>CFBundleName</key>
  #             <string>EtsyTrackr</string>
  #             <key>CFBundlePackageType</key>
  #             <string>APPL</string>
  #             <key>CFBundleShortVersionString</key>
  #             <string>1.0</string>
  #             <key>LSMinimumSystemVersion</key>
  #             <string>10.10</string>
  #             <key>NSHighResolutionCapable</key>
  #             <true/>
  #         </dict>
  #         </plist>
  #         EOF
          
  #         # Create DMG
  #         brew install create-dmg
  #         create-dmg \
  #           --volname "EtsyTrackr" \
  #           --volicon "icon.png" \
  #           --window-pos 200 120 \
  #           --window-size 600 300 \
  #           --icon-size 100 \
  #           --icon "EtsyTrackr.app" 175 120 \
  #           --hide-extension "EtsyTrackr.app" \
  #           --app-drop-link 425 120 \
  #           "EtsyTrackr.dmg" \
  #           "EtsyTrackr.app"

  #     - name: Upload DMG Release Asset
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: /private/tmp/etsytrackr_build/EtsyTrackr.dmg
