name: Build Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executables
        run: python build.py

      - name: Create Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: installer.iss

      - name: Upload Single-File Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/onefile/EtsyTrackr.exe

      - name: Upload Installer Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: Output/EtsyTrackr_Setup.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2 python3-tk python3-dev flatpak flatpak-builder imagemagick

      - name: Setup Flatpak environment
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build AppImage
        run: python build.py --mode appimage

      - name: Upload AppImage Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/appimage/EtsyTrackr-x86_64.AppImage

      - name: Build OneFile
        run: python build.py --mode onefile

      - name: Build Flatpak
        run: python build_flatpak.py

      - name: Upload Flatpak Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/flatpak/EtsyTrackr.flatpak

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pyinstaller
          pip install -r requirements.txt
          brew install create-dmg

      - name: Free up disk space
        run: |
          sudo rm -rf /Library/Developer/CommandLineTools
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/share/swift
          brew cleanup

      - name: Build DMG
        run: |
          # Build DMG (this will build the app bundle first)
          python build.py --mode dmg
          
          if [ -f "dist/dmg/EtsyTrackr.dmg" ]; then
            echo "DMG file created successfully"
            ls -l dist/dmg/EtsyTrackr.dmg
          else
            echo "DMG file not found!"
            exit 1
          fi

      - name: Upload DMG Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/dmg/EtsyTrackr.dmg
