name: Build Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
          check-latest: true
          allow-prereleases: false
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6==6.6.1
          pip install pandas==2.1.4 matplotlib==3.8.2 plotly==5.18.0 python-dotenv==1.0.0 PyPDF2==3.0.1 pillow==10.1.0 numpy==1.26.3
          pip install pyinstaller==6.3.0
          pip list
      - name: Verify Python and PySide6
        run: |
          python --version
          python -c "import PySide6; print('PySide6 version:', PySide6.__version__)"
          python -c "import PySide6; print('PySide6 location:', PySide6.__file__)"
          python -c "from PySide6 import QtCore; print('QtCore location:', QtCore.__file__)"
          dir "$env:pythonLocation\Lib\site-packages\PySide6"
      - name: Build executable
        run: |
          python build.py
      - name: Check executable
        run: |
          dir dist\EtsyTrackr.exe /s
          echo "Executable size:"
          powershell -Command "Get-Item dist\EtsyTrackr.exe | Select-Object Length"
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/EtsyTrackr.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
          check-latest: true
          allow-prereleases: false
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6==6.6.1
          pip install pandas==2.1.4 matplotlib==3.8.2 plotly==5.18.0 python-dotenv==1.0.0 PyPDF2==3.0.1 pillow==10.1.0 numpy==1.26.3
          pip install pyinstaller==6.3.0
          pip list
      - name: Build executable
        run: python build.py
      - name: Create DMG
        run: |
          cd dist
          mkdir -p EtsyTrackr.app/Contents/MacOS
          mv EtsyTrackr EtsyTrackr.app/Contents/MacOS/
          hdiutil create -volname "EtsyTrackr" -srcfolder EtsyTrackr.app -ov -format UDZO EtsyTrackr.dmg
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/EtsyTrackr.dmg

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
          check-latest: true
          allow-prereleases: false
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PySide6==6.6.1
          pip install pandas==2.1.4 matplotlib==3.8.2 plotly==5.18.0 python-dotenv==1.0.0 PyPDF2==3.0.1 pillow==10.1.0 numpy==1.26.3
          pip install pyinstaller==6.3.0
          pip list
      - name: Build executable
        run: python build.py
      - name: Create AppImage
        run: |
          cd dist
          mkdir -p EtsyTrackr.AppDir/usr/bin
          mv etsytrackr EtsyTrackr.AppDir/usr/bin/
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage EtsyTrackr.AppDir EtsyTrackr.AppImage
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/EtsyTrackr.AppImage
